spring:
  h2:
    console:
      enabled: true
#spring.profiles: default
#demo.security.jwt:
#  tokenExpirationTime: 15 # Number of minutes
#  refreshTokenExpTime: 60 # Minutes
#  tokenIssuer: http://krkimb.com
#  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
#
#spring.jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#
#spring.h2.console.enabled: true
#
#spring.datasource.url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1'
